### ISSUE TITLE
Bounce reply send_message()

### ISSUE THREAD

**Issue by JakeRuss** [jimhester/gmailr#9] opened 2014-10-15 17:48 UTC
I created a new gmail acount and then followed the setup instructions [here](https://github.com/jimhester/gmailr).

Running `gmail_auth()` with the .json file, opens a webpage and then I approve that credential.

```r 
library(gmailr)

msg <-  mime() %>%
from("notify.jwr@gmail.com") %>%
to("jake.w.russ@gmail.com") %>%
text_body("Please don't reject my package")

send_message(msg)
```
This just returns a bounce reply to the notify.jwr account that says message not sent. I apologize for not having a MWE.

**Comment by ctbrown** [comment] 2015-01-07 20:38
I can confirm this bug as well.  It seems to result from the magrittr style of composing messages.  If you do it in standard R format the way JennyBC did in her send-mail-with-r tutorial, it does not seem to have a problem. This works:

```
test_email <- mime(
    To = "PUT_A_VALID_EMAIL_ADDRESS_HERE",
    From = "PUT_YOUR_EMAIL_ADDRESS_HERE",
    Subject = "this is just a gmailr test",
    body = "Can you hear me now?")
ret_val <- send_message(test_email)
ret_val$status_code 
```
This does not: 

```
mime() %>% ...
```
It is interesting to the methods produce different objects.  My guess is the problem is with `text_body` which seems to put place the body in the parts slot.  Presumably to handle multi-part messages?

**Comment by ctbrown** [comment] 2015-01-08 07:29
Also, this appears to be related to issue #11.  You probably get two-for-one here.

**Comment by jimhester** [comment] 2015-11-02 13:51
I think this is fixed now, I no longer have this issue.

**Closed by jimhester** 2015-11-02 13:51 UTC
